### ISSUE TITLE
Azure-Patch Operation not working

### ISSUE THREAD

**Issue by KalyaniBharatha** [Captain-P-Goldfish/scim-for-keycloak#110]
Hi Team, 

I am using scim-for-keycloak: kc-20-b1, i started testing with Azure entra, so user creation, deletion working good, but user update(patch operation) is not working.Attaching the screenshot, could you please help me on this.
![AzurePatchError](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/36667030/072989e8-d516-4b85-9781-99e90af9296e)

Thanks,
Kalyani

**Comment by Captain-P-Goldfish** [comment]
I guess you are using the github version, downloaded from the releases section?
This is not supported anymore. I would recommend using the kc-20 version from here: https://scim-for-keycloak.de/

I also tested the mentioned request. It is working with kc-20-b7. But I would also recommend to update the keycloak version. Several bugs have been fixed since keycloak 20. And kc-20 and 21 will not receive updates anymore.

**Comment by KalyaniBharatha** [comment]
Thanks for the reply, and yes i have downloaded form github only, so can you tell me how to check out kc-20-b7 version?

**Comment by Captain-P-Goldfish** [comment]
it is described on the mainpage of https://scim-for-keycloak.de:
see summary **How to get the SCIM for Keycloak plugin?**

**Comment by KalyaniBharatha** [comment]
thanks
