### ISSUE TITLE
Azure AD SCIM 2.0 protocol compliance

### ISSUE THREAD

**Issue by JessThrysoee** [Captain-P-Goldfish/scim-for-keycloak#26]
Azure AD has a feature flag for closer [SCIM 2.0 protocol compliance](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-config-problem-scim-compatibility#flags-to-alter-the-scim-behavior)

On [Use-with-Microsoft-Azure-AD](https://github.com/Captain-P-Goldfish/scim-for-keycloak/wiki/Use-with-Microsoft-Azure-AD) in step 5, perhaps suggest adding the `aadOptscim062020` query param in the provisioning, to fix some of the Patch behaviour, e.g

```
Tenant URL = https://your.keycloak-server.ch/auth/realms/beta/scim/v2/?aadOptscim062020 
```

A similar suggestion is probably appropriate in SCIM-SDK on [Support-for-MS-Azure-requests](https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/Support-for-MS-Azure-requests) ?

**Comment by Captain-P-Goldfish** [comment]
I checked on the microsoft documentation and most cases are not releavant anymore because they are supported by SCIM-SDK 1.12.1 except for one specific case.
A patch-operation of the following form:

```json
{
          "op": "replace",
          "value": {
              "displayName": "Bjfe",
              "name.givenName": "Kkom",
              "name.familyName": "Unua",
              "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:employeeNumber": "Aklq"
          }
      }
```

would still ignore the attributes `name.givenName`and `name.familyName`.
All other cases should be supported even without the extra parameter or am I wrong?
