### ISSUE TITLE
Support for cluster mode

### ISSUE THREAD

**Issue by Xapgkop4uk** [Captain-P-Goldfish/scim-for-keycloak#56]
Does the package work for keycloak running in cluster mode?

**Comment by Captain-P-Goldfish** [comment]
The cluster mode should be supported to some degree:

I opened this issue once: https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/4 in order to show that there is one problem in cluster mode:

The SCIM endpoints do use the internal keycloak API and therefore the infinispan cache is used during runtime. But the configuration within the keycloak web admin is a different thing. This is totally customized code without infinispan customization. So if you would happen to deactivate SCIM for a specific realm it will not be synchronized to your second node if the SCIM endpoints were at least accessed once on your second node.

But as long as you do not change the configuration within the keycloak webadmin console it there should be no problems with running in cluster mode.
