### ISSUE TITLE
Keycloak 19 - Issue with Theming when SCIM is enabled

### ISSUE THREAD

**Issue by udayskm** [Captain-P-Goldfish/scim-for-keycloak#66]
Tried to enable SCIM functionality/theme in Keycloak 19 version and observed the following

![image](https://user-images.githubusercontent.com/47665247/194236922-43b9e2dc-9841-4633-a420-cb92eed0c270.png)

Post applying SCIM theme and refresh the page

![image](https://user-images.githubusercontent.com/47665247/194237337-267aba86-90a3-43ff-8ac4-85643aebc4ba.png)

Clicking on "Go to the home page>> ", theme is reverted to Keycloak 18 version.

![image](https://user-images.githubusercontent.com/47665247/194237854-8f3f2867-73d6-4271-8e0a-9b5176f9350f.png)

_**Note:**_
This is not a show-stopper/blocker, it is just about theme.

**Comment by Captain-P-Goldfish** [comment]
that is actually expected behaviour.
The old theme is written in angular-js and the new keycloak admin-theme is written in React. The React theme does not have any possibilities to add additional menus yet. So until keycloak does not have a solution for this problem it is not possible to migrate the SCIM menu to the new admin theme.
