### ISSUE TITLE
Noob Question: Why SCIM while keycloak already provide rest api to manage users and groups

### ISSUE THREAD

**Issue by WestFarmer** [Captain-P-Goldfish/scim-for-keycloak#81]
The only advantage I can think of is:
1. SCIM is a standard.

Can you guys enlighten me a bit more.

**Comment by Captain-P-Goldfish** [comment]
Hi,

the reason as you say because SCIM is a standard. Other providers like AWS, Microsoft Azure AD, Atlassian etc. are implementing SCIM exactly for the purpose of user and group provisioning. So as long as you do not have the need to link such services with your keycloak there is no need for you to use SCIM. But as soon as you want user and group provisioning in cloud environments or similiar this is the solution to go.
