### ISSUE TITLE
Affiliation between users and groups synced from AzureAD to keycloak is lost

### ISSUE THREAD

**Issue by iFengWang** [Captain-P-Goldfish/scim-for-keycloak#90]
Why when I synchronize users and groups in AzureAD to my keycloak18.0.0 through kc-18-b1, the users and groups are synchronized successfully, but I find that the affiliation between users and groups, and between groups Relationships are all lost. Has anyone else encountered this problem? Please advise! Thank you very much! !

**Comment by Captain-P-Goldfish** [comment]
Sorry it seems that I have missed this ticket.
Did you solve the problem?
The OpenSource version is legacy by the way and no longer supported. But I have a slight idea what happened. Did this happen in the synchronization process between Azure and keycloak?

**Comment by fgrtl** [comment]
I have encountered the same issue in the synchronization process between Entra ID and Keycloak.
Do you have any idea why this happened?
Thanks in advance!

**Comment by Captain-P-Goldfish** [comment]
Yes, I have a pretty good idea and I am currently working on this. The problem is a combination of the current patch-implementation of the SCIM-SDK and the usage of concurrent  patch-updates. 

The current version of the patch-implementation calls basically the get-endpoint, patches the result und calls the update-method. If a concurrent request is sent at the same time. The old-resource is read, the other patch-request succeeds and is saved in the database. The concurrent request has read the memberships of the old resource and is therefore deleting the membership that was just saved.

I am almost finished with restructuring the patch-implementation in the SCIM-SDK. If this is done I will fix it in the SCIM-for-keycloak plugin.

**Comment by fgrtl** [comment]
Sorry to ask, but will these changes also be published in the open source project?
We are currently stuck at Keycloak 18 due to our project.
Thanks for your response!

**Comment by Captain-P-Goldfish** [comment]
sorry, but this will not be added to the OpenSource version. I have not enough capacity anymore to support older versions too. And the github version differs a lot from the version at https://scim-for-keycloak.de so it will also not be possible to copy and paste the solution here.

**Comment by fgrtl** [comment]
Total understandable, thanks for the answers!

**Comment by Captain-P-Goldfish** [comment]
fixed, but not released yet. Will be available in version 2.0.0
